### PR TITLE
feat: use initialization page and providers

### PR DESCRIPTION
**Pull request by riscait**
## 🙌 What's Done

- Use initialization page/providers

### Overview
(Japanese)

- https://zenn.dev/altiveinc/articles/riverpod-provider-initialization

## ✍️ What's Not Done

- 

## 🤼 Desired Review Method

- [ ] Correction Commit
- [ ] Pair programming

> [!NOTE]
> It is possible that a reviewer's will may cause a method to be implemented that is not selected.

## Pre-launch Checklist
- [x] I have reviewed my own code.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I updated/added relevant documentation (doc comments with ///).

### CODE REVIEW

**Comment by k-nkmr** [comment]
@riscait 

I’m sorry, but the Figma link you provided keeps loading and doesn’t open for me. Would it be possible to share a screenshot or something similar instead? 🙇🏻‍♀️

**Comment by riscait** [comment]
@k-nkmr 
I was able to open it in a browser incognito window, so it doesn't seem to be a problem with the URL or my account.
It's a lot of work to take screenshots of all the pages...
But the slides are what I shared at the study session the other day👌

**Review by naipaka — APPROVED** [review]
LGTM

**Review by k-nkmr — APPROVED** [review]
LGTM

**Pull request merged**
